---
title: "R Notebook"
output: html_notebook
---



```{r}
water_data_raw<-read_csv("FSUCML Seawater Monitoring System Data/CMLAHWQ_20230629-20250501.csv")
```


```{r}

water_edit<-read_csv("FSUCML Seawater Monitoring System Data/CMLAHWQ_20230629-20250501.csv", skip=2)

#daily_avg <- water_edit |> mutate(DateTimeStamp=mdy_hm(DateTimeStamp), date=as.Date(DateTimeStamp)) |> group_by(date) |> summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))


#bad_rows <- water_edit$DateTimeStamp[is.na(mdy_hm(water_edit$DateTimeStamp))]
#print(bad_rows)

```



```{r}
#gets daily average of all columns for each day

daily_avg2 <- water_edit |> mutate(DateTimeStamp = parse_date_time(DateTimeStamp, orders = c("mdy HM", "mdy HMS", "mdy")),date = as.Date(DateTimeStamp)) |> group_by(date) |> summarise(across(where(is.numeric), ~ mean(.x, na.rm = TRUE)))

daily_avg2<-daily_avg2 |> drop_na()
#drops rows with NA 

#checks if any rows has NA
any(is.na(daily_avg2$date))




```



```{r}
#remove the columns that are not needed, like historical,provincialplus

daily_avg2<-daily_avg2 |> select(-Historical,-ProvisionalPlus)

#separates out date column into separate columns for year, month, day values
daily_avg_cleaned<- daily_avg2 |> mutate(date=ymd(date), year=year(date), month=month(date), day=day(date))

unique(daily_avg_cleaned$month)


```

```{r}

averages_year<-daily_avg_cleaned |> group_by(month,year) |> summarise(across(-c(day,date),~ mean(.x, na.rm = TRUE))) #averages by months, removes day and date column for being averaged 

summer_months_avg<-averages_year |>filter(month>=4 & month<=8) |>  group_by(month)
#print(summer_months_avg)

```


```{r}

summer_avg_pivot<- summer_months_avg |> pivot_longer(cols=-c(month,year), names_to = "Water_Variable", values_to = "Value") 

summer_avg_pivot |> ggplot(aes(x=month,y=Value, color=factor(year)))+geom_line()+geom_point()+facet_wrap(~ Water_Variable, scales="free_y", labeller=labeller(Water_Variable=c(Temp="Temp(°C)", Sal="Salinity(ppt)", ph="pH", DO_mgl= "DO (mg/L", SpCond="Specific Conductivity(mS/cm)", Depth="Depth(m)", DO_pct="DO_pct(percent saturation", Turb="Turbidity")))+labs(color="Year", x= "Month", y="Water Variable Values")+ scale_x_continuous(breaks = 1:12, labels = month.abb)


```


```{r}

averages_year_pivot<-averages_year |> pivot_longer(cols=-c(month,year), names_to = "Water_Variable", values_to = "Value") 

averages_year_pivot |> ggplot(aes(x=month,y=Value, color=factor(year)))+geom_line()+geom_point()+facet_wrap(~ Water_Variable, scales="free_y", labeller=labeller(Water_Variable=c(Temp="Temp(°C)", Sal="Salinity(ppt)", ph="pH", DO_mgl= "DO (mg/L", SpCond="Specific Conductivity(mS/cm)", Depth="Depth(m)", DO_pct="DO_pct(percent saturation)", Turb="Turbidity")))+labs(color="Year", x= "Month", y="Water Variable Values")+ scale_x_continuous(breaks = 1:12, labels = month.abb)



```




```{r}

monthly_range_pivot<-daily_avg_cleaned |> pivot_longer(cols = c(Temp, SpCond, pH, Sal, Depth, Turb, DO_pct, DO_mgl), names_to = "Water_Variable", values_to = "Value")

monthly_range_pivot |> ggplot(aes(x=factor(month), y=Value, fill=factor(year)))+geom_boxplot()+ facet_wrap(~Water_Variable, scales="free_y",labeller=labeller(Water_Variable=c(Temp="Temp(°C)", Sal="Salinity(ppt)", pH="pH", DO_mgl= "DO (mg/L", SpCond="Specific Conductivity(mS/cm)", Depth="Depth(m)", DO_pct="DO_pct(percent saturation)", Turb="Turbidity")))+ scale_x_discrete(labels = month.abb)+labs(x= "Month",fill="Year", y="Water Variable")


```

```{r}

monthly_range_pivot |> ggplot(aes(x=date,y=Value,color=factor(year)))+geom_line()+facet_wrap(~Water_Variable,scales="free_y")+ labs(color="Year")


```
 















































